blank_issues_enabled: false
contact_links:
  - name: Discord Support
    url: https://discord.gg/FEmNcz7QwP
    about: Join our Discord for support, updates, and announcements.
  - name: RSBot Documentation
    url: https://silkroad-developer-community.github.io/RSBot/
    about: Read tutorials, guides, and documentation for RSBot.
